### ISSUE TITLE
apidom-reference: URI resolution for `file://` protocols

### ISSUE THREAD

**Issue by char0n** [swagger-api/apidom#2606]
When setting baseURI in e.g. to -> `https://api.dev.swaggerhub.com/apis/X/Y/1`
Then if we have `file:///proc/1/environ` the resulting resolved uri will have form of `https://api.dev.swaggerhub.com/proc/1/environ`.

---

This is wrong. the `file://` protocol can be stripped only after resolution has happened, not before.

**Comment by rainum** [comment]
The `file://` protocol resolution happens in the following way:

1. If the URI is a file protocol, then it's resolved as is using Node.js `fs` module.
2. If the URI has http/https protocol, then it's resolved as is using the Axios HTTP client.

Unfortunately, the Node's `fs` module doesn't support remote file protocol, eg: `file://nnsc.nsf.net/rfc/rfc959.txt`
. we need to handle it separately.

[`toBaseURI`](https://github.com/swagger-api/apidom/blob/main/packages/apidom-reference/src/dereference/strategies/openapi-3-0/visitor.ts#L101) method is used to resolve the base URI of the given URI. In the case of the file protocol, the base URIi will most likely still have http protocol, here is an example: if the following arguments are passed to the `toBaseURI` method:
- `baseURL = http://localhost:8123/root.json`
- `uri = file:///ex.json`
    
The result will be the following: `http://localhost:8123/ex.json`. This is not an ideal solution, since it doesn't handle the case when the file is remote, hence preventing us from crossing cross-protocol boundaries. But at the same time, it allows us to resolve remote files with the help of HTTP request.

After chatting with @char0n  we decided to keep it as is for now and revisit it later if needed.
