### ISSUE TITLE
apidom-reference: URL resolution doesn't understand combination of special character in URL 

### ISSUE THREAD

**Issue by char0n** [swagger-api/apidom#3923]
Example URL: https://api.sap.com/odata/1.0/catalog.svc/APIContent.APIs('SAP_ICSM_StudyService')/$value?type=json

apidom-reference will reject to resolve/deference/parse the URL.

**Comment by char0n** [comment]
This issue has been caused by file extension issue described in https://github.com/swagger-api/apidom/issues/4298. As URL mentioned in this issue don't have file extension, parser plugins failed to parse it. After fixing https://github.com/swagger-api/apidom/issues/4298, this issue no longer manifests.

**Comment by rainum** [comment]
Thanks for the update, @char0n! Here are a couple of other thoughts from my side.

Playground failed to process the example URL due to the CORS error:

![image](https://github.com/user-attachments/assets/afc671fd-da87-4069-a2a8-ab3811480bd9)

When I recreated the same complex path in my personal repo, it worked just fine:

https://github.com/user-attachments/assets/bb6fa2e9-c45d-4b00-8358-9089cc66b1df
